### ISSUE TITLE
Latest pip breaks "pip install" command

### ISSUE THREAD

**Issue by evanpierre** [raganmd/touchdesigner-hueControl#14]
Latest pip breaks "pip install" command. Issue being discussed here: https://github.com/pypa/pip/issues/7209

Fix:
Add to beginning of command -> "**python -m** pip install..."

Solution discussion here: https://stackoverflow.com/questions/58451650/pip-no-longer-working-after-update-error-module-object-is-not-callable

**Comment by Polyterative** [comment]
any news?

**Comment by raganmd** [comment]
Should now be address with a recent update - windows for sure. needs testing on macOS
