### ISSUE TITLE
Missing script files for install

### ISSUE THREAD

**Issue by mimiyin** [raganmd/touchdesigner-hueControl#16]
Is there a new process for installing dependencies? There are no longer script files inside of dev/dep. I was able to get it working by installing phue manually but would love to use this for a beginner class and want to iron out the install issues. Thank you for creating this!

**Comment by raganmd** [comment]
What's your OS @mimiyin?

On Windows the process should look like:

- create a new project folder
- save your toe file to that folder
- drag the hue tox into your project
- save your toe file
- quit and restart the td project or bypass and un-bypass the TD component

Testing the above, that creates all of the required pieces. 

Currently, the install process does rely on a OS installation of python 3 that matches with TD's built in version. This uses a subprocess call to launch a pip install process. It could be a mismatch there if you're seeing some issues.

**Comment by raganmd** [comment]
For reference, in the comp there's `extHelperMOD` this contains all of the helper and installation process code for pulling these outside dependencies into TD. There's a long going conversation on the Derivative forum about how best to work with python dependencies, and how to pull in outside libraries.

**Comment by mimiyin** [comment]
Thx for the quick response. I just tried it on Windows and it works like a charm. But still doesn't work on my macOS Catalina (10.15.7) The install script doesn't appear to run at all. Terminal should pop open for a second? The first time I toggle "Cooking" I get an additional error that complains about not being able to find "requirements.txt". The error disappears on subsequent toggles.

**Comment by raganmd** [comment]
Ahh, okay. I don't have a mac handy to debug this on until tomorrow.

macOS is a little pickier about how it handles some of these elements, and it's a good brain buster to get this playing nicely. 

When is your class planned to start? I can work on a fix here, but it might be the weekend before I can get this knot untangled.
