### ISSUE TITLE
no module name  'phue'

### ISSUE THREAD

**Issue by vladdrac6** [raganmd/touchdesigner-hueControl#17]
I am getting an error on the TOX: no module name  'phue'

Touchdesigner 2021.15800
MacOs 10.15.7

I believe I followed the instructions for installing phue correctly. I couldn't find the script "\dev\dep\update-dep-python-mac.sh". I may be out of my depth.

Can you offer any guidance? thanks much

<img width="911" alt="Screen Shot 2022-01-23 at 8 32 41 PM" src="https://user-images.githubusercontent.com/66344276/150708204-5e7bd6c0-5ec3-4f97-ab13-8f971a775d2e.png">
h

**Comment by raganmd** [comment]
The update .sh file should be generated automatically. 

It is important that you have python 3.7 installed. I usually start by making sure OS python elements are setup correctly, then start to dig in on the TouchDesigner side of the equation. 

There's a good summary of working with external python libraires for the 2019 TD Summit. You can see the workshop for that one here:
https://mir.works/td-summit-2019-external-python-libraries

**Comment by vladdrac6** [comment]
Thank you for the super fast response. I made sure I have python 3.7 installed and watched the videos. The script was not automatically generated. Can you offer any other guidance? I would really love to have this integration but my python knowledge is zero.

**Comment by vladdrac6** [comment]
got it working, thanks for the help!

**Comment by raganmd** [comment]
killer - sorry it's taken me a minute to reply to you, I'm glad it all got sorted. :)
