### ISSUE TITLE
.sh to pull mac python modules

### ISSUE THREAD

**Issue by raganmd** [raganmd/touchdesigner-hueControl#9]
Check mac scripts for pulling python deps

**Comment by raganmd** [comment]
still not working correctly - needs more attention in mac land to figure this one out

**Comment by radialbalance** [comment]
Still not working - needed to add python folder manually

**Comment by raganmd** [comment]
@zo3trope - sigh. Okay. I'll try to figure out what's going on here. Lame.

**Comment by raganmd** [comment]
Fixed in dev branch - will merge to Master shortly
